### PR TITLE
REFACTOR: Remove `_.merge`

### PR DESCRIPTION
**Pull request by jbrw**
As per https://github.com/discourse/discourse/pull/10566/commits

### CODE REVIEW

**Comment by eviltrout** [comment]
One downside here is that `deepMerge` only exists in `tests-passed`/`master` and not in `beta` or `stable`, so this would break the plugin for those people.

@jbrw one potential solution to this issue is to add `deepMerge` to the `stable` and `beta` branches.

**Comment by ZogStriP** [comment]
@jbrw did you backport `deepMerge`?

**Comment by jbrw** [comment]
@ZogStriP It has been backported this morning: https://github.com/discourse/discourse/pull/10764

Would anyone try to upgrade their plugins without upgrading to the latest version of stable or beta?

**Comment by eviltrout** [comment]
@jbrw it's basically impossible to upgrade your plugins without also upgrading your discourse, so we can count on deepMerge being present now.

**Pull request merged**
